### ISSUE TITLE
Define the resource buffers needed by the fusion power plant

### ISSUE THREAD

**Issue by gonuke** [uw-reti/tricycle#3]
Add the definition of the resource buffers that will be used in the fusion power plant archetype, and associated initialization variables that should be included in the archetype's definition via the `#pragma cyclus` calls.

**Comment by dean-krueger** [comment]
I guess I used the wrong keyword in PR #9. Closing this issue as complete.

**Comment by gonuke** [comment]
I think it likes "closes" or "fixes" as verbs

**Comment by gonuke** [comment]
Revisiting this after some discussion:

Feed inventories - material can be purchased from outside:
* blanket feed
* tritium feed

Product inventories - material can be sold to outside:
* tritium product
* he-3 product

Waste inventories - material can be transferred to outside:
* blanket waste

Active inventories - not engaged in outside trading - could be just material objects
* core blanket
* core tritium
* sequestered tritium

Am I missing any, @dean-krueger ?

**Comment by dean-krueger** [comment]
I think that about sums it up for what we had in mind for this version of FPP, with some other options for later versions being things like Deuterium feed/product, etc (which we don't need to implement right now I think). The one thing I'll say is that I think it makes sense for the concept of the "Core" to be transient. For example, things might live inside their appropriate buffers and then only get "pulled into the core" for operations that need to be performed on them, such as breeding, burning, transmuting, etc, before they're moved back into to the appropriate place. That may be a larger discussion, though?

**Comment by gonuke** [comment]
I'm not sure how transient you mean... if your blanket is only turning over occasionally, then material should reside there. Each turnover should remove some to waste and replace it with feed. I don't think blanket material should ever flow from core back to feed.
